export const COUNTRY_CODES: { code: string; country: string; min: number; max: number }[] = [
    { code: "+1", country: "USA/Canada", min: 10, max: 10 },
    { code: "+7", country: "Russia/Kazakhstan", min: 10, max: 10 },
    { code: "+20", country: "Egypt", min: 9, max: 9 },
    { code: "+27", country: "South Africa", min: 9, max: 9 },
    { code: "+30", country: "Greece", min: 10, max: 10 },
    { code: "+31", country: "Netherlands", min: 9, max: 9 },
    { code: "+32", country: "Belgium", min: 8, max: 9 },
    { code: "+33", country: "France", min: 9, max: 9 },
    { code: "+34", country: "Spain", min: 9, max: 9 },
    { code: "+36", country: "Hungary", min: 9, max: 9 },
    { code: "+39", country: "Italy", min: 10, max: 10 },
    { code: "+40", country: "Romania", min: 9, max: 9 },
    { code: "+41", country: "Switzerland", min: 9, max: 9 },
    { code: "+44", country: "UK", min: 10, max: 11 },
    { code: "+45", country: "Denmark", min: 8, max: 8 },
    { code: "+46", country: "Sweden", min: 7, max: 9 },
    { code: "+47", country: "Norway", min: 8, max: 8 },
    { code: "+48", country: "Poland", min: 9, max: 9 },
    { code: "+49", country: "Germany", min: 10, max: 11 },
    { code: "+52", country: "Mexico", min: 10, max: 10 },
    { code: "+53", country: "Cuba", min: 9, max: 9 },
    { code: "+54", country: "Argentina", min: 10, max: 10 },
    { code: "+55", country: "Brazil", min: 10, max: 11 },
    { code: "+56", country: "Chile", min: 9, max: 9 },
    { code: "+57", country: "Colombia", min: 10, max: 10 },
    { code: "+58", country: "Venezuela", min: 10, max: 10 },
    { code: "+60", country: "Malaysia", min: 9, max: 10 },
    { code: "+61", country: "Australia", min: 9, max: 9 },
    { code: "+62", country: "Indonesia", min: 9, max: 11 },
    { code: "+63", country: "Philippines", min: 10, max: 10 },
    { code: "+64", country: "New Zealand", min: 9, max: 9 },
    { code: "+65", country: "Singapore", min: 8, max: 8 },
    { code: "+66", country: "Thailand", min: 9, max: 9 },
    { code: "+81", country: "Japan", min: 9, max: 10 },
    { code: "+82", country: "South Korea", min: 9, max: 10 },
    { code: "+84", country: "Vietnam", min: 9, max: 10 },
    { code: "+86", country: "China", min: 11, max: 11 },
    { code: "+90", country: "Turkey", min: 10, max: 10 },
    { code: "+91", country: "India", min: 10, max: 10 },
    { code: "+92", country: "Pakistan", min: 10, max: 10 },
    { code: "+93", country: "Afghanistan", min: 9, max: 10 },
    { code: "+94", country: "Sri Lanka", min: 9, max: 9 },
    { code: "+95", country: "Myanmar", min: 7, max: 9 },
    { code: "+98", country: "Iran", min: 10, max: 10 },
    { code: "+211", country: "South Sudan", min: 9, max: 9 },
    { code: "+212", country: "Morocco", min: 9, max: 10 },
    { code: "+213", country: "Algeria", min: 9, max: 9 },
    { code: "+216", country: "Tunisia", min: 8, max: 8 },
    { code: "+218", country: "Libya", min: 9, max: 9 },
    { code: "+220", country: "Gambia", min: 7, max: 7 },
    { code: "+221", country: "Senegal", min: 9, max: 9 },
    { code: "+222", country: "Mauritania", min: 8, max: 8 },
    { code: "+223", country: "Mali", min: 8, max: 8 },
    { code: "+224", country: "Guinea", min: 9, max: 9 },
    { code: "+225", country: "Côte d’Ivoire", min: 10, max: 10 },
    { code: "+226", country: "Burkina Faso", min: 8, max: 8 },
    { code: "+227", country: "Niger", min: 8, max: 8 },
    { code: "+228", country: "Togo", min: 8, max: 8 },
    { code: "+229", country: "Benin", min: 8, max: 8 },
    { code: "+230", country: "Mauritius", min: 8, max: 8 },
    { code: "+231", country: "Liberia", min: 8, max: 9 },
    { code: "+232", country: "Sierra Leone", min: 8, max: 8 },
    { code: "+233", country: "Ghana", min: 9, max: 9 },
    { code: "+234", country: "Nigeria", min: 10, max: 10 },
    { code: "+235", country: "Chad", min: 8, max: 8 },
    { code: "+236", country: "CAR", min: 8, max: 8 },
    { code: "+237", country: "Cameroon", min: 8, max: 8 },
    { code: "+238", country: "Cape Verde", min: 7, max: 7 },
    { code: "+239", country: "São Tomé & Príncipe", min: 7, max: 7 },
    { code: "+240", country: "Equatorial Guinea", min: 7, max: 7 },
    { code: "+241", country: "Gabon", min: 7, max: 8 },
    { code: "+242", country: "Republic of the Congo", min: 8, max: 8 },
    { code: "+243", country: "DR Congo", min: 9, max: 9 },
    { code: "+244", country: "Angola", min: 9, max: 9 },
    { code: "+245", country: "Guinea-Bissau", min: 7, max: 9 },
    { code: "+246", country: "British Indian Ocean Territory", min: 7, max: 7 },
    { code: "+247", country: "Ascension Island", min: 5, max: 7 },
    { code: "+248", country: "Seychelles", min: 7, max: 7 },
    { code: "+249", country: "Sudan", min: 9, max: 9 },
    { code: "+250", country: "Rwanda", min: 9, max: 9 },
    { code: "+251", country: "Ethiopia", min: 9, max: 9 },
    { code: "+252", country: "Somalia", min: 8, max: 9 },
    { code: "+253", country: "Djibouti", min: 8, max: 8 },
    { code: "+254", country: "Kenya", min: 9, max: 9 },
    { code: "+255", country: "Tanzania", min: 9, max: 9 },
    { code: "+256", country: "Uganda", min: 9, max: 9 },
    { code: "+257", country: "Burundi", min: 8, max: 8 },
    { code: "+258", country: "Mozambique", min: 9, max: 9 },
    { code: "+260", country: "Zambia", min: 9, max: 9 },
    { code: "+261", country: "Madagascar", min: 9, max: 9 },
    { code: "+262", country: "Reunion & Mayotte", min: 9, max: 9 },
    { code: "+263", country: "Zimbabwe", min: 9, max: 9 },
    { code: "+264", country: "Namibia", min: 9, max: 9 },
    { code: "+265", country: "Malawi", min: 9, max: 9 },
    { code: "+266", country: "Lesotho", min: 7, max: 7 },
    { code: "+267", country: "Botswana", min: 8, max: 8 },
    { code: "+268", country: "Eswatini", min: 7, max: 7 },
    { code: "+269", country: "Comoros", min: 7, max: 7 },
    { code: "+290", country: "Saint Helena", min: 5, max: 7 },
    { code: "+291", country: "Eritrea", min: 7, max: 7 },
    { code: "+297", country: "Aruba", min: 7, max: 7 },
    { code: "+298", country: "Faroe Islands", min: 7, max: 7 },
    { code: "+299", country: "Greenland", min: 6, max: 6 },
    { code: "+350", country: "Gibraltar", min: 9, max: 9 },
    { code: "+351", country: "Portugal", min: 9, max: 9 },
    { code: "+352", country: "Luxembourg", min: 8, max: 9 },
    { code: "+353", country: "Ireland", min: 9, max: 9 },
    { code: "+354", country: "Iceland", min: 7, max: 8 },
    { code: "+355", country: "Albania", min: 9, max: 9 },
    { code: "+356", country: "Malta", min: 8, max: 8 },
    { code: "+357", country: "Cyprus", min: 8, max: 8 },
    { code: "+358", country: "Finland", min: 9, max: 10 },
    { code: "+359", country: "Bulgaria", min: 9, max: 9 },
    { code: "+370", country: "Lithuania", min: 8, max: 9 },
    { code: "+371", country: "Latvia", min: 8, max: 8 },
    { code: "+372", country: "Estonia", min: 7, max: 8 },
    { code: "+373", country: "Moldova", min: 8, max: 8 },
    { code: "+374", country: "Armenia", min: 8, max: 8 },
    { code: "+375", country: "Belarus", min: 9, max: 9 },
    { code: "+376", country: "Andorra", min: 6, max: 8 },
    { code: "+377", country: "Monaco", min: 8, max: 8 },
    { code: "+378", country: "San Marino", min: 8, max: 9 },
    { code: "+379", country: "Vatican City", min: 8, max: 8 },
    { code: "+380", country: "Ukraine", min: 9, max: 9 },
    { code: "+381", country: "Serbia", min: 8, max: 9 },
    { code: "+382", country: "Montenegro", min: 8, max: 8 },
    { code: "+383", country: "Kosovo", min: 8, max: 8 },
    { code: "+385", country: "Croatia", min: 9, max: 9 },
    { code: "+386", country: "Slovenia", min: 8, max: 9 },
    { code: "+387", country: "Bosnia & Herzegovina", min: 8, max: 9 },
    { code: "+389", country: "North Macedonia", min: 8, max: 8 },
    { code: "+420", country: "Czech Republic", min: 9, max: 9 },
    { code: "+421", country: "Slovakia", min: 9, max: 9 },
    { code: "+423", country: "Liechtenstein", min: 9, max: 9 },
    { code: "+500", country: "Falkland Islands", min: 5, max: 7 },
    { code: "+501", country: "Belize", min: 7, max: 7 },
    { code: "+502", country: "Guatemala", min: 8, max: 8 },
    { code: "+503", country: "El Salvador", min: 8, max: 8 },
    { code: "+504", country: "Honduras", min: 8, max: 8 },
    { code: "+505", country: "Nicaragua", min: 8, max: 8 },
    { code: "+506", country: "Costa Rica", min: 8, max: 8 },
    { code: "+507", country: "Panama", min: 7, max: 8 },
    { code: "+508", country: "Saint Pierre & Miquelon", min: 6, max: 6 },
    { code: "+509", country: "Haiti", min: 8, max: 8 },
    { code: "+590", country: "Guadeloupe", min: 9, max: 9 },
    { code: "+591", country: "Bolivia", min: 8, max: 8 },
    { code: "+592", country: "Guyana", min: 7, max: 7 },
    { code: "+593", country: "Ecuador", min: 9, max: 9 },
    { code: "+594", country: "French Guiana", min: 9, max: 9 },
    { code: "+595", country: "Paraguay", min: 9, max: 9 },
    { code: "+596", country: "Martinique", min: 9, max: 9 },
    { code: "+597", country: "Suriname", min: 7, max: 7 },
    { code: "+598", country: "Uruguay", min: 8, max: 8 },
    { code: "+599", country: "Caribbean Netherlands", min: 7, max: 9 }
];
